name: Clean Up

on:
  schedule:
    # every 23 o'clock
    - cron: 0 23 * * * 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install --only=prod 
      - run: npm start cleanup
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          KNIGHTLY_BOT_GIST_STORE: ${{ secrets.KNIGHTLY_BOT_GIST_STORE }}
